# Connectivity Plan Purpose, Approach, and Vision {#approach}

## Purpose and Approach {#purpose}
The following Watershed Connectivity Remediation Plan (WCRP) represents the culmination of a six-month collaborative planning effort, the overall aim of which is to build collaborative partnerships within the Horsefly River watershed to improve connectivity for anadromous salmon and the livelihoods that they support, including the continued sustenance, cultural, and ceremonial needs of the Northern Secwépemc people. This 20-year plan was developed to identify priority actions that the Horsefly River WCRP planning team (see Table 1 for a list of team members) will undertake between 2021-2040 to conserve and restore fish passage in the watershed, through crossing remediation, lateral barrier remediation, dam remediation, and barrier prevention strategies.

WCRPs are long-term, actionable plans that blend local stakeholder and rightsholder knowledge with innovative GIS analyses to gain a shared understanding of where remediation efforts will have the greatest benefit for anadromous salmon. The planning process is inspired by the [Conservation Standards](http://conservationstandards.org/wp-content/uploads/sites/3/2020/12/CMP-Open-Standards-for-the-Practice-of-Conservation-v4.0-English.pdf) (v.4.0), which is a conservation planning framework that allows planning teams to systematically identify, implement, and monitor strategies to apply the most effective solutions to high priority conservation problems. There is a rich history of connectivity and fish habitat planning and remediation work in the Horsefly River watershed that this WCRP builds upon, including work undertaken by the BC Fish Passage Technical Working Group, the Northern Secwepemc te Qelmucw (NStQ) and member communities, the Horsefly River Roundtable, and other local organizations (Masse Environmental Consultants Ltd. 2018; S. Hocquard, Steve Hocquard Consulting, pers. comm.).

The planning team compiled existing barrier location and assessment data, habitat data, and previously identified priorities, and combined this with local and Indigenous knowledge to create a strategic watershed-scale plan to improve connectivity. To expand on this work the Horsefly River WCRP planning team applied the WCRP planning framework to define the "thematic" scope of freshwater connectivity and refine the "geographic" scope to identify only those portions of the watershed where barrier prioritization will be conducted, and subsequent remediation efforts will take place. Additionally, the team selected target fish species, assessed their current connectivity status in the watershed, defined concrete goals for gains in connectivity, and developed a priority list of barriers for remediation to achieve those goals. While the current version of this plan is based on the best-available information at the time of publishing, WCRPs are intended to be “living plans” that are updated regularly as new information becomes available, or if local priorities and contexts change. As such, this document should be interpreted as a current snap-shot in time, and future iterations of this WCRP will build upon the material presented in this plan to continuously improve barrier remediation for migratory fish in the Horsefly River watershed. For more information on how WCRPs are developed, see Mazany-Wright et al. 2021c.

## Vision Statement {#vision}
<span style="color:#00827F"> _Healthy, well-connected streams and rivers within the Horsefly River watershed support thriving populations of migratory fish, improving the overall ecosystem health of the watershed. In turn, these fish provide the continued sustenance, cultural, and ceremonial needs of the Northern Secwépemc people, as they have since time immemorial. Both residents and visitors to the watershed work together to mitigate the negative effects of anthropogenic aquatic barriers, improving the resiliency of streams and rivers for the benefit and appreciation of all._ </span>